sudo: false
language: erlang
otp_release:
    - 18.3
    - 19.3
    - 20.3
    - 21.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - ./rebar3 get-deps
  - ./rebar3 compile
  - ./rebar3 eunit
